// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

namespace Server.Migrations
{
    [DbContext(typeof(PirisContext))]
    [Migration("20200209092338_changeClient")]
    partial class changeClient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Server.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressOfRegistration")
                        .IsRequired();

                    b.Property<string>("AddressOfResidence")
                        .IsRequired();

                    b.Property<string>("Authority")
                        .IsRequired();

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("CityOfRegistration")
                        .IsRequired();

                    b.Property<string>("CityOfResidence")
                        .IsRequired();

                    b.Property<DateTime>("DateOfIssue");

                    b.Property<string>("Disability")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("HomePhone");

                    b.Property<string>("JobPlace");

                    b.Property<string>("MaritalStatus")
                        .IsRequired();

                    b.Property<string>("MobilePhone");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Nationality")
                        .IsRequired();

                    b.Property<string>("PassportId")
                        .IsRequired();

                    b.Property<string>("PassportNumber")
                        .IsRequired();

                    b.Property<string>("PassportSeries")
                        .IsRequired();

                    b.Property<string>("Patronymic")
                        .IsRequired();

                    b.Property<bool>("Pensioner");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired();

                    b.Property<string>("Position");

                    b.Property<double>("Salary");

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Server.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("Server.Models.Сity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
