// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

namespace Server.Migrations
{
    [DbContext(typeof(PirisContext))]
    [Migration("20200204172641_CLients2")]
    partial class CLients2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Server.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Authority");

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("City");

                    b.Property<DateTime>("DateOfIssue");

                    b.Property<string>("Disability");

                    b.Property<string>("Email");

                    b.Property<string>("HomePhone");

                    b.Property<string>("JobPlace");

                    b.Property<string>("MaritalStatus");

                    b.Property<string>("MobilePhone");

                    b.Property<string>("Name");

                    b.Property<string>("Nationality");

                    b.Property<string>("PassportId");

                    b.Property<string>("PassportNumber");

                    b.Property<string>("PassportSeries");

                    b.Property<string>("Patronymic");

                    b.Property<bool>("Pensioner");

                    b.Property<string>("PlaceOfBirth");

                    b.Property<string>("PlaceOfResidence");

                    b.Property<string>("Position");

                    b.Property<bool>("Salary");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
